### ISSUE TITLE
FRQ #2 STEP TRACKER

### ISSUE THREAD

**Issue by saumyapalk23** [saumyapalk23/saumyafastpages#7]
**Hacks**
- [x] Build tester method (public static void main) for Person Pojo. Test zero argument and all argument constructor. build toString method to display attributes of the class.

![toString](https://user-images.githubusercontent.com/89223433/204179155-2930635e-8174-4240-8a2f-90ad71868eb7.png)

- [x] Build other attributes into POJO that where mentioned in project dialog at the beginning of this blog. 

- **Added more arguments**

![moreargs](https://user-images.githubusercontent.com/89223433/204190033-d5754f4c-7a3f-455e-81b1-b14084b13652.png)
- **More personal attributes**
![personattr](https://user-images.githubusercontent.com/89223433/204190042-56fa68bd-d3f4-4c34-b6a7-42947fa75601.png)

- [x] Add 1 or more APIs. Use Issues to plan and track work.
![getageapi](https://user-images.githubusercontent.com/89223433/204206133-42017aab-d106-4fdd-96c7-19b4d80bd8c5.png)

- **Testing Issues**
![testingissues](https://user-images.githubusercontent.com/89223433/204231692-babe3c04-94fe-4419-8e0a-9bfffb4d5aeb.png)

![error](https://user-images.githubusercontent.com/89223433/204337365-e0336de5-ee43-40ff-a800-0be4026710e8.png)

- [x] Correct the BUG in setStats! Currently, it won't let you do more than one date.
![setstats](https://user-images.githubusercontent.com/89223433/204206150-9f77ab32-682a-42d9-9bbc-8b7fcfae2fcf.png)
